from __future__ import annotations
import uuid
from datetime import datetime
from typing import List, Dict, Any

from core import memory
from core.schemas import AgentOutput
from core.llm import ask as llm_ask, is_available as llm_ready


def _build_decision_report(best: Dict, all_scored: List[Dict], risks: Dict[str, Dict]) -> str:
    name = best.get("token_name", "Unknown")
    ticker = best.get("ticker", "TKN")
    score = best.get("_final_score", 0)
    risk = risks.get(best.get("id", ""), {})

    if llm_ready():
        prompt = f"""You are the CEO of a crypto token launch firm. Write a sharp, confident investment decision report for launching {name} (${ticker}).

Token concept: {best.get('one_line_narrative', '')}
Target community: {best.get('target_community', '')}
Meme angle: {best.get('meme_angle', '')}
Opportunity score: {score:.1f}/100
Meme potential: {best.get('meme_potential', 0)}/100
Community potential: {best.get('community_potential', 0)}/100
Timing: {best.get('timing', 0)}/100
Risk score: {risk.get('overall_risk_score', 5)}/10

Write a 3-paragraph CEO decision memo: why this token, why now, and the key risks to manage. Be direct, crypto-native in tone. Max 200 words."""
        ai_memo = llm_ask(prompt, fallback="")
        if ai_memo:
            return f"""# CEO Decision Report
Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

## RECOMMENDATION: {name} (${ticker})
**Final Opportunity Score:** {score:.1f}/100

{ai_memo}

### Required Next Actions
1. Human founder approval
2. Brand package review and approval
3. Smart contract audit
4. Social infrastructure setup (Telegram, Discord)
5. First 7-day content calendar approval

---
*All decisions require human approval before execution.*
"""

    return f"""# CEO Decision Report
Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

## RECOMMENDATION: {name} (${ticker})

**Final Opportunity Score:** {score:.1f}/100

### Why {name}?
- Trend velocity: {best.get('virality_score', 0):.0f}/100
- Meme potential: {best.get('meme_potential', 0):.0f}/100
- Community potential: {best.get('community_potential', 0):.0f}/100
- Timing score: {best.get('timing', 0):.0f}/100
- Technical feasibility: {best.get('technical_feasibility', 0):.0f}/100

### Risk Profile
- Overall risk: {risk.get('overall_risk_score', 5):.1f}/10
- IP risk: {risk.get('ip_trademark_risk', 0):.1f}/10
- Marketing risk: {risk.get('marketing_risk_score', 0):.1f}/10

### Narrative
{best.get('one_line_narrative', '')}

### Why Now
{best.get('why_now', '')}

### Rejected Alternatives
{chr(10).join(f"- {i.get('token_name')}: score {i.get('_final_score',0):.1f} — {i.get('_rejection_reason','lower overall score')}" for i in all_scored[1:3])}

### Required Next Actions
1. Human founder approval
2. Brand package review and approval
3. Smart contract audit
4. Social infrastructure setup (Telegram, Discord)
5. First 7-day content calendar approval
6. Launch window confirmation

---
*This report is generated by the CEO Agent. All decisions require human approval before execution.*
"""


class CEOAgent:
    NAME = "ceo_agent"

    def run(self, ideas: List[Dict], scores: List[Dict], risk_reviews: List[Dict]) -> AgentOutput:
        if not ideas:
            return AgentOutput(
                timestamp=datetime.utcnow(),
                agent_name=self.NAME,
                input_summary="No token ideas available",
                output=None,
                score=0,
                next_recommended_action="Run collect-trends then generate-token-ideas first",
            )

        score_map = {s["token_idea_id"]: s for s in scores}
        risk_map  = {r["subject_id"]: r for r in risk_reviews}

        scored_ideas = []
        for idea in ideas:
            iid = idea.get("id", "")
            s = score_map.get(iid, {})
            r = risk_map.get(iid, {})
            final = s.get("final_opportunity_score", 0)
            if not final:
                from core.scoring import compute_opportunity_score
                opp = compute_opportunity_score(
                    token_idea_id=iid,
                    trend_strength=idea.get("virality_score", 60),
                    meme_potential=idea.get("meme_potential", 60),
                    community_potential=idea.get("community_potential", 60),
                    novelty=idea.get("novelty", 60),
                    timing=idea.get("timing", 60),
                    technical_feasibility=idea.get("technical_feasibility", 80),
                    brand_strength=idea.get("brand_strength", 60),
                    risk_score=r.get("overall_risk_score", 5) * 10,
                )
                final = opp.final_opportunity_score

            scored_ideas.append({**idea, "_final_score": final})

        ranked = sorted(scored_ideas, key=lambda x: x["_final_score"], reverse=True)
        best = ranked[0]

        for idea in ranked[1:]:
            idea["_rejection_reason"] = (
                f"lower opportunity score ({idea['_final_score']:.1f} vs {best['_final_score']:.1f})"
            )

        launch_checklist = {
            "trend_validated": True,
            "token_concept_approved": False,
            "brand_package_approved": False,
            "risk_review_completed": len(risk_reviews) > 0,
            "social_infrastructure_prepared": False,
            "first_content_calendar_ready": False,
            "community_channels_ready": False,
            "smart_contract_generated": False,
            "smart_contract_tests_passed": False,
            "tokenomics_reviewed": False,
            "launch_report_generated": True,
            "human_approval_received": False,
        }

        summary_report = _build_decision_report(best, ranked, risk_map)

        decision = {
            "id": f"decision_{str(uuid.uuid4())[:8]}",
            "recommended_token_id": best.get("id"),
            "recommended_token_name": f"{best.get('token_name')} (${best.get('ticker')})",
            "selection_reasons": [
                f"Highest final opportunity score: {best['_final_score']:.1f}/100",
                f"Meme potential: {best.get('meme_potential', 0):.0f}/100",
                f"Community potential: {best.get('community_potential', 0):.0f}/100",
                f"Timing: {best.get('timing', 0):.0f}/100 — trend is live",
            ],
            "rejected_alternatives": [
                {"id": i.get("id"), "name": i.get("token_name"), "score": i.get("_final_score"), "reason": i.get("_rejection_reason", "")}
                for i in ranked[1:]
            ],
            "score_breakdown": {
                "final_opportunity_score": best["_final_score"],
                "meme_potential": best.get("meme_potential", 0),
                "community_potential": best.get("community_potential", 0),
                "timing": best.get("timing", 0),
                "technical_feasibility": best.get("technical_feasibility", 0),
                "risk_score": risk_map.get(best.get("id",""), {}).get("overall_risk_score", 5),
            },
            "risks_considered": best.get("possible_risks", []),
            "required_next_actions": [
                "Human founder approval required before proceeding",
                "Brand package review and approval",
                "Smart contract audit",
                "Social infrastructure setup",
                "First 7-day content calendar approval",
                "Trademark/legal review",
            ],
            "launch_checklist_status": launch_checklist,
            "human_approval_status": "pending",
            "decided_at": datetime.utcnow().isoformat(),
            "summary_report": summary_report,
        }

        existing = memory.load_decisions()
        existing.append(decision)
        memory.save_decisions(existing)

        return AgentOutput(
            timestamp=datetime.utcnow(),
            agent_name=self.NAME,
            input_summary=f"Evaluated {len(ideas)} token ideas, selected {best.get('token_name')}",
            output=decision,
            score=best["_final_score"],
            next_recommended_action="Review CEO decision in dashboard. Approve to proceed to contract generation.",
        )
